### ISSUE TITLE
Broken assets

### ISSUE THREAD

**Issue by zlakomanoff** [artkost/yii2-trumbowyg#4]
yii\base\InvalidParamException: The file or directory to be published does not exist: /srv/http/example/vendor/bower-asset/trumbowyg/dist in /srv/http/example/vendor/yiisoft/yii2/web/AssetManager.php:456

**Comment by JiLiZART** [comment]
Thanks! Can u provide some additional information, yii version, and which version of trumbowyg installed in your project?

**Comment by zlakomanoff** [comment]
Looks like i fount the issue
```
  - Installing bower-asset/trumbowyg (2.8.0.x-dev 7c10a85): Cloning 7c10a85611 from cache
    7c10a8561146bb1c5d5ce13dfbbf9c786b0f4660 is gone (history was rewritten?)
    Failed to download bower-asset/trumbowyg from source: Failed to execute git checkout '7c10a8561146bb1c5d5ce13dfbbf9c786b0f4660' -- && git reset --hard '7c10a8561146bb1c5d5ce13dfbbf9c786b0f4660' --

fatal: reference is not a tree: 7c10a8561146bb1c5d5ce13dfbbf9c786b0f4660

    Now trying to download from dist
  - Installing bower-asset/trumbowyg (2.8.0.x-dev 7c10a85): Downloading (100%)         
  - Updating artkost/yii2-trumbowyg (dev-master dc9f7a8 => 2.0):  Checking out 846356d475
```

**Comment by JiLiZART** [comment]
Seems composer `composer-asset-plugin` somehow installs `2.8.0.x-dev` branch of Trumbowyg.
Very sad, I didn't find any workaround. 
I bump version of Trumbowyg to 2.7.1 until 2.8.0 will be released. 
Now you can try to `composer update`

**Comment by zlakomanoff** [comment]
Yii2 team not use composer-asset-plugin anymore, you can read more at https://asset-packagist.org
The problem on trymbowyg npm package side, after package is download gulp isnt start.
I run gulp manually, and package work like a charm.

**Comment by JiLiZART** [comment]
@zlakomanoff After release 2.x version of this package is still problem exists for you?
